# https://github.com/k1LoW/octocov?tab=readme-ov-file#configuration
coverage:
  paths:
    - coverage.xml
codeToTestRatio:
  code:
    - "**/*.py"
  test:
    - "tests/**/*.py"
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
