[mypy]

; https://mypy.readthedocs.io/en/latest/config_file.html

; Import discovery

ignore_missing_imports = True


; Disallow dynamic typing

; disallow_any_expr = True
disallow_any_decorated = True
; disallow_any_explicit = True
; disallow_any_generics = True
disallow_subclassing_any = True


; Untyped definitions and calls

disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True


; None and optional handling

no_implicit_optional = True


; Configuring warnings

warn_unused_ignores = True
warn_return_any = True
