# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.1@sha256:3bec97fe09041df2f6ac50e208993ebf7c41c1474add7c774bb59d4f96cf01a5
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv
            pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: run tests
          command: |
            set -eu
            pipenv run lint
            pipenv run test
