name: octocov
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  octocov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Enable caching
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Test
        run: uv run poe test

      - name: Coverage
        run: uv run poe coverage-xml

      # See also: https://github.com/k1LoW/octocov-action
      - name: Report coverage with octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .octocov.yml
